### ISSUE TITLE
一直显示“加载中，请稍候”

### ISSUE THREAD

**Issue by alovin** [insoxin/qrpay#1]
使用的BT宝塔，新建网站后，无论是使用全静态环境，还是php5.6和php7.0，点击生成后，都是一直显示“加载中，请稍候”，这是我哪里设置错误吗？

**Comment by insoxin** [comment]
请更新到现在的最新版本

**Comment by wait12** [comment]
最新版本也是一直加载中

**Comment by insoxin** [comment]
@wait12 是我的演示网站出现这种情况的吗?

**Comment by wait12** [comment]
你的演示站，我搭建都是加载中。

**Comment by insoxin** [comment]
@wait12 截图
