### ISSUE TITLE
WX二维码解析失效

### ISSUE THREAD

**Issue by rickychaw** [insoxin/qrpay#11]
RT
error decoding QR Code

**Comment by insoxin** [comment]
21:22:48测试正常,你再尝试一下吧

**Comment by rickychaw** [comment]
能给个你测试的地址吗？我在你的演示站试同样是不行的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 晚上9:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [insoxin/qrpay] WX二维码解析失效 (#11)





 
Closed #11.

**Comment by insoxin** [comment]
> 能给个你测试的地址吗？我在你的演示站试同样是不行的
> […](#)

演示站可以的啊

**Comment by insoxin** [comment]
你保存收款码到本地,别截图,完整图片试试

**Comment by rickychaw** [comment]
腾讯云服务器 https://api.isoyu.com/qrpay/

腾讯云COS https://qrpay.isoyu.com/

这两个微信收款码都不行，换了浏览器不行，用手机浏览器也不行。  直接保存到手机和从手机发送到电脑的，没有截图。
之前部署好是可以的，今天试了试不行了

**Comment by insoxin** [comment]
> 腾讯云服务器 https://api.isoyu.com/qrpay/
> 
> 腾讯云COS https://qrpay.isoyu.com/
> 
> 这两个微信收款码都不行，换了浏览器不行，用手机浏览器也不行。 直接保存到手机和从手机发送到电脑的，没有截图。
> 之前部署好是可以的，今天试了试不行了

我这边一切正常,手机电脑,最近也没人反馈无法解析二维码,无法确定你那边原因啊,你先暂时使用  https://cli.im/deqr 这个吧

**Comment by rickychaw** [comment]
好的谢谢，我排查一下本地网络
