### ISSUE TITLE
wx扫码失败

### ISSUE THREAD

**Issue by Fittrue** [insoxin/qrpay#13]
已停止访问该网页

是被举报了吗

**Comment by insoxin** [comment]
> 已停止访问该网页
> 
> 是被举报了吗

我图吗？还有你扫的码图片

**Comment by Fittrue** [comment]
是我在https://qrpay.isoyu.com/上面生成了我的收款码，然后就不能用微信扫出来
![%E2(5EE8ASHGF(O4(E 6QL1](https://user-images.githubusercontent.com/31371538/112605240-0d81b980-8e52-11eb-879b-2c131383838a.png)

**Comment by insoxin** [comment]
你生成的码,发下我试试,我这里无法复现

**Comment by Fittrue** [comment]
![下载](https://user-images.githubusercontent.com/31371538/112605544-618c9e00-8e52-11eb-99a2-2509288ce82b.jpg)

**Comment by insoxin** [comment]
> 是我在[https://qrpay.isoyu.com/上面生成了我的收款码，然后就不能用微信扫出来](https://qrpay.isoyu.com/%E4%B8%8A%E9%9D%A2%E7%94%9F%E6%88%90%E4%BA%86%E6%88%91%E7%9A%84%E6%94%B6%E6%AC%BE%E7%A0%81%EF%BC%8C%E7%84%B6%E5%90%8E%E5%B0%B1%E4%B8%8D%E8%83%BD%E7%94%A8%E5%BE%AE%E4%BF%A1%E6%89%AB%E5%87%BA%E6%9D%A5)
> ![%E2(5EE8ASHGF(O4(E 6QL1](https://user-images.githubusercontent.com/31371538/112605240-0d81b980-8e52-11eb-879b-2c131383838a.png)

有个,原因是里面的短链接,那个用的第三方

**Comment by Fittrue** [comment]
这个应该怎么解决啊？

**Comment by insoxin** [comment]
> 这个应该怎么解决啊？
http://x8r.cn/

用的这个网站接口

他备案了苏ICP备2020060997号

微信还拦截了
没办法

**Comment by insoxin** [comment]
我再找找新接口

**Comment by Fittrue** [comment]
谢谢，麻烦版主大大了

**Comment by insoxin** [comment]
> 谢谢，麻烦版主大大了

已经换了新接口,你重新生成下

**Comment by Fittrue** [comment]
> > 谢谢，麻烦版主大大了
> 
> 已经换了新接口,你重新生成下

这波wx好了，zfb又凉了 
zfb提示：该链接存在安全风险

**Comment by insoxin** [comment]
> > > 谢谢，麻烦版主大大了
> > 
> > 
> > 已经换了新接口,你重新生成下
> 
> 这波wx好了，zfb又凉了
> zfb提示：该链接存在安全风险

稍等,我再试试其他接口

**Comment by insoxin** [comment]
好了好了,换了新的,测试微信支付宝正常

**Comment by Fittrue** [comment]
> 好了好了,换了新的,测试微信支付宝正常

现在可以了，麻烦了
