### ISSUE TITLE
老哥

### ISSUE THREAD

**Issue by junweiWu** [insoxin/qrpay#15]
能提供一下imaotai的接口信息吗

**Comment by junweiWu** [comment]
或者能否教一下获取接口的思路……感谢🙏

**Comment by insoxin** [comment]
若不会反编译, 抓包也抓不到?

**Comment by junweiWu** [comment]
两个都试了，都失败了，承认我菜求教

**Comment by junweiWu** [comment]
抓包https加密不知道咋整，反编译出来的文件没找到请求路径

**Comment by junweiWu** [comment]
大哥能给个vx好友位吗😳

**Comment by insoxin** [comment]
Android:HttpCanary
iOS:Thor

Windows:Fiddler
macOS:Charles

均可以抓包https 

搜索 软件加 https

**Comment by junweiWu** [comment]
> Android:HttpCanary
> iOS:Thor
> 
> Windows:Fiddler
> macOS:Charles
> 
> 均可以抓包https 
> 
> 搜索 软件加 https 

试了fiddler和charles抓到的内容看不出什么东西，我再试试吧

**Comment by junweiWu** [comment]
> Android:HttpCanary
> iOS:Thor
> 
> Windows:Fiddler
> macOS:Charles
> 
> 均可以抓包https 
> 
> 搜索 软件加 https 

大佬你能抓到获取验证码的接口吗

**Comment by junweiWu** [comment]
试了一天硬是弄不出来，获取验证码，和登录的请求抓不到。其他接口抓到了。求教大佬

**Comment by fbi178** [comment]
希望老大放出详细教程
