### ISSUE TITLE
这样子是不是有风险？

### ISSUE THREAD

**Issue by baiyutang** [insoxin/qrpay#2]
方便虽然是方便，但是在用户角度是否有比较大的风险？

**Comment by insoxin** [comment]
万物都没有绝对的安全，这款程序功能并非我原创首发还有使用动态语言(如php)编写类似相关，github可以搜的到

程序原理不用我说，也能猜到是根据浏览器ua显示不同页面

本程序纯html且开源，已经杜绝了编程语言带来的大部分漏洞

再者如果是用户单人使用还是比较推荐个人版的，把链接手动PS到想要的二维码模板中就行😁

当然如果有好的建议欢迎提出，我也会持续关注 谢谢
