### ISSUE TITLE
js报错

### ISSUE THREAD

**Issue by breakmyself** [insoxin/qrpay#5]
你好，我在使用宝塔部署的三合一的二维码出现js报错，请检查下
`Failed to load resource: the server responded with a status of 404 (Not Found)
shdapao.com/:1 A cookie associated with a cross-site resource at http://baidu.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`
导致部署后无法正常生成二维码

**Comment by insoxin** [comment]
无法加载资源：服务器的状态为404（未找到）。shdapao.com/:1在http://baidu.com/上设置了与跨站点资源关联的cookie，但未设置SameSiteattribute。 如果将跨站点请求的Cookie设置为SameSite = NoneandSecure，则Chrome的未来版本将仅提供具有跨站点请求的Cookie。 您可以在“应用程序”&gt;“存储”&gt;“ Cookies”下的开发人员工具中查看Cookie，并在https://www.chromestatus.com/feature/5088147346030592和https://www.chromestatus.com/feature/5633521622188032上查看更多详细信息。


shdapao.com &nbsp; 这是你的站吗? &nbsp; js不存在跨域问题 &nbsp;都是引用本地的







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: breakmyself <notifications@github.com&gt;
发送时间: 2020年3月2日 14:44
收件人: insoxin/qrpay <qrpay@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[insoxin/qrpay] js报错 (#5)




你好，我在使用宝塔部署的三合一的二维码出现js报错，请检查下
 Failed to load resource: the server responded with a status of 404 (Not Found) shdapao.com/:1 A cookie associated with a cross-site resource at http://baidu.com/ was set without the SameSiteattribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set withSameSite=NoneandSecure. You can review cookies in developer tools under Application&gt;Storage&gt;Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
 导致部署后无法正常生成二维码
